config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  
  root "articles#index"
  # get '/articles', to: "articles#index"

  # get "/articles/:id", to: "articles#show"
  get '/article/:id/like', to: 'articles#like', as: 'like'

  resources :categories
  resources :articles do
    resources :comments
  end

end

app/models/account.rb
class Account < ApplicationRecord
  before_save { self.email = email.downcase }
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :articles 
    has_many :comments    
    
    
end
# validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
#  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :account
	belongs_to :category
	has_many :likes
	has_many :comments, dependent: :destroy
	has_one_attached :avatar
	validates :account_id, presence: true
	validates :title, presence: true
	validates :body, presence: true, length: { minimum: 10 }
	has_rich_text :body

	def liked?(account)
	
		!!self.likes.find{|like| like.account_id == account.id}
	end
end

app/models/category.rb
class Category < ApplicationRecord
	validates :category, presence: true 
	has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :account
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :account
  belongs_to :article
  validates :account_id, uniqueness: {scope: :article_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :authenticate_account!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @categories = Category.all
    category = params[:category]
    if !category.nil?
      @articles = Article.where(:category_id => category)
    else
    @articles = Article.all.reverse()
  end
    # render json: @articles
  end

  def show
    # binding.pry
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end        

  def create
    
    @article = Article.new(article_params)
    # binding.pry
    @article.account = current_account
    
    if @article.save
      redirect_to root_path
    else
      render :new, status: :unprocess_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article= Article.find(params[:id])
    if @article.update(article_params)
      redirect_to root_path
      else
        render :edit, status: :unprocess_entity
        end 
  end 

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end


  def like
    @article = Article.all.find(params[:id])
    Like.create(account_id: current_account.id, article_id: @article.id)
    redirect_to article_path(@article)
  end


private

def article_params
  params.require(:article).permit(:title, :body, :avatar, :category_id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all


    # render json: @categories
  end

  def show
     @category = Category.find(params[:id])

  end

  def new
    @category = Category.new
  end

  def create
    
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new, status: :unprocess_entity
    end
  end

  def edit
     @category = Category.find(params[:id])
  end

  def update
    @category= Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
      else
        render :edit, status: :unprocess_entity
        end 
  end 

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, status: :see_other
  end


private

def category_params
  params.require(:category).permit(:category)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
	@article = Article.find(params[:article_id])
	@comment = @article.comments.create(comment_params)
	redirect_to article_path(@article)
end

private 

	def comment_params
		params.require(:comment).permit(:commenter, :account_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  


  <% if blob.image? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>


  <% if blob.video? %>
    <%= video_tag url_for(blob.attachable), preload: "auto", controls: "controls", width: "640", height: "360" %>
  <% end %>


  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<%= form_with model: article  do |form| %>
  
<div class="mb-3">

    <%= form.label :avatar, :class=>"form-label" %><br>
    <%= form.file_field :avatar, :class=>"form-control" %><br>

</div>
<div class="mb-3">

    <%= form.label :title, :class=>"form-label" %><br>
    <%= form.text_field :title, :class=>"form-control" %><br>
    </div>

<div class="mb-3">
  
    <%= form.label :body, :class=>"form-label" %><br>
    <%= form.rich_text_area :body, :class=>"form-control" %><br>

   </div> 
    <div class="mb-3">
     <%= form.label :Category, :class=>"form-label" %><br>
    <%= form.select :category_id,  Category.all.map{|c| [c.category, c.id]} %><br>
  </div>

 <div class="mb-3 ">
    <%= form.submit 'Create Article', :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/articles/_navbar.html.erb
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="https://www.w3villa.com/">W3Villa</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
   
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 profile-menu"> 
        <li class="nav-item dropdown">
           <% if account_signed_in? %>
            <li class="fs-6 text-white mt-2"><%=  current_account.email  %></li>
            <% end%>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-user"></i>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if account_signed_in? %>
            <li><%= link_to "logout", "/accounts/sign_out",  :class => " dropdown-item", method: :delete %>
            </li>
             <% else %>
             <li><%= link_to "Signup", "/accounts/sign_up", :class => "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
             <li><%= link_to "Login", "/accounts/sign_in", :class => "dropdown-item" %></li>
             <% end %>
          </ul>
        </li>
     </ul>
    </div>
  </div>
</nav>

app/views/articles/edit.html.erb
<h1>Edit Articles</h1>


<%= render "form", article: @article %>

<br>
<%= link_to "back", article_path  %>

app/views/articles/index.html.erb
<div>

  <div class="container-fluid position-fixed bg-white" style="z-index: 1;">
    <div class="row">    
      <%= render "navbar" %>
      </div>
    </div>




        <div class="container">
          <div class="row">
            <div class="col-4 mt-5 " style="margin-top: 100px !important;">
              <div class="category mt-5 position-fixed mt-5 tm" style="
              font-size: small;">
              <a href="#" class="list-group-item list-group-item-action active bg-dark" aria-current="true">
                Categories
              </a>
              <% @categories.each do |category| %>
              <ul class="list-group  list-unstyled">
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto ">
                    <div class="fw-bold"><%= link_to category.category, articles_path(:category=> category.id), :class=>"text-decoration-none " %></div>
                  </div>
                  <span class="badge bg-primary rounded-pill mx-3 "><%= category.articles.count %></span></li>
                </ul>
                <% end %>
                <div class="allcategory mt-2 px-3">
                  <%= link_to "All Categories", articles_path %>
                </div>
              </div>
            </div>
            
            <div class="col-4 ">
              <div class=" mt-5   d-flex justify-content-center">
                <div class=" px-5">
                  <% @articles.each do |article| %>
                  <div class="card ftn mt-5 justify-content-center">
                    <%= link_to article do %>
                    <%= image_tag article.avatar, :class=>"card-img-top"  if article.avatar.attached? %>
                    <% end %>
                    <div class="card-body">
                      <%= link_to article.title, article, :class=>"text-decoration-none" %><br>
                      <small>Category: 
                        <%= link_to article.category.category,  article, :class=>"text-decoration-none" %><br>
                      </small>
                      <small>Created by: <%= article.account.email if article.account %>,
                        <%= time_ago_in_words(article.created_at) %> ago, 
                        last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                      </div></div>


                      <div class="card ">
                        <div class="card-body">


                          <span class="space-comment2"></span>
                          <small class=""><i class="fa fa-commenting-o"></i> Comment</small>

                          <span class="space-comment"></span>
                          <small class=""><i class="fa fa-commenting-o"></i> <%= article.comments.count %> </small>
                          <span class="space-comment2"></span>
                          <small class=""><i class="fa fa-thumbs-o-up"></i><%= article.likes.count %> </small>

                        </div>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="col-4 " style="margin-top: 100px !important;">
                  <div class="event  position-fixed mx-5">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item ">Events</li>
                      <li class="list-group-item">
                        <div class=" text-center">
                         <%= link_to "create Article..", new_article_path, :class=>"text-decoration-none" %>
                       </div>
                     </li>
                     <li class="list-group-item">
                       <div class="input-group mb-4">
                        <input type="search" placeholder="What're you searching for?" aria-describedby="button-addon5" class="form-control">
                        <div class="input-group-append sm">
                          <button id="button-addon5" type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>          
        </div>

app/views/articles/new.html.erb
<i class="fa fa-arrow-left mt-2 px-2" aria-hidden="true"></i><%= link_to "back", articles_path , :class=>"text-decoration-none text-dark px-2" %>
<h3 class="text-center mt-3">New Article</h3>
<div class="container border w-50 mt-2">

<%= render "form", article: @article %>

</div>  

app/views/articles/show.html.erb
<div class="container-fluid position-fixed bg-white" style="z-index: 1;">
    <div class="row">
     <%= render "navbar" %>
    </div>
</div><br>
    <div class="mt-5">
        <ul class="list-group">
   <% if current_account != @article.account %> 
  <li class="list-group-item "><i class="fa fa-arrow-left" aria-hidden="true"></i><%= link_to "back", articles_path , :class=>"text-decoration-none text-dark px-2" %></li>     
  <% end %>
   </ul>

    </div>
    <div class="container-fluid text-center mt-5">
      <small><strong>Created by</strong></small><br>
      <%= @article.account.email if @article.account %>
      <p>
      On<%= @article.created_at.strftime("%B %d %Y, %l:%M%P") %>
      </p>
    </div>      
<div class="container">
  <div class="row">
    <div class="col">
    </div>
    <div class="col">
     <div class="container mt-5 ">
      <div class="card  mt-5 " style="width: 40rem;">
      <div class="card-body">
      <small><%= image_tag @article.avatar, :class=>"card-img-top"  if @article.avatar.attached? %></small>
      <div class="card-body">
      <small> <%=  @article.title %></small><br>
      <div class="container-fluid">
      <small><%=  @article.body %></small>

   
      </div>
      <small><strong>Category :</strong><%=  @article.category.category %></small>
              <div class ="link-show float-end">
     <% if current_account == @article.account %> 
      <li class="list-group"><%= link_to "Edit", edit_article_path(@article), :class=>"text-decoration-none" %></li>
  <li class="list-group"><%= link_to "Destroy", article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  }, :class=>"text-decoration-none" %></li>
  <li class="list-group "><%= link_to "back", articles_path , :class=>"text-decoration-none" %></li> 
  <% end %>
  </div>
      </div>
      </div>
      </div>
    </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>

  


<div class="container mt-5">
  <div class="row">
    <div class="col comment">
        <h2>Comments (<%= @article.comments.count %>)</h2>
        <% @article.comments.each do |comment| %>
        <p><strong><%=  comment.account.email %>:</strong><%= comment.commenter %></p>
        <% end %>
        <%= form_with model: [ @article, @article.comments.build ] do |form| %>
        <%= form.hidden_field :account_id, :value => current_account.id %>
        <p><%= form.label :comment %><br><%= form.text_field :commenter %></p>
        <p><%= form.submit %></p>
         <div class="col ">   
        <% end %>
         </div>
      <div class="like-show">
          <Strong><h6>Likes (<%= @article.likes.count %> )</h6></strong>
        </div> 
        <% if account_signed_in? %>
            <% if @article.liked?(current_account) %>
                <%= link_to like_path(@article), :class=>"likes", method: 'puts', disabled: true do %>
                <small><i class="fa fa-thumbs-o-up px-1  fa-lg mt-3"></i> like</small>
            <% end %>
            <% else %>
              <%= link_to like_path(@article), :class=>"likes", method: 'puts' do %>
              <small class=""><i class="fa fa-thumbs-o-up fa-lg mt-3"></i> like</small>
              <% end %>
            <% end %>
          <% end%>  
        </div>
  </div>
</div>      

<footer class="bg-dark text-center text-white mt-5" >
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="">W3Villa.com</a>
  </div>
  <!-- Copyright -->
</footer>




    
         
      
                              

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <%# category.errors.full_messages.each do |message| %>
          <li><%#= message %></li>
        <%# end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-6">
    <%= form.label :category %>
    <%= form.text_field :category, class: "form-control" %>
  </div><br>
  <div class="actions">
    <%= form.submit  class: "btn-submit" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Categories</h1>


<%= render "form", category: @category %>

<br>
<%= link_to "back", category_path  %>

app/views/categories/index.html.erb
<h2> All Categories</h2>
<br>
<div class="container">
  <div class="row">
    <% @categories.each do |category| %>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h3>
             <%= link_to category.category, category %>
            </h3>   
          </div>        
        </div>
      </div>
    <% end %>  
  </div>  
</div>
<br>
<%= link_to 'New Category', new_category_path , class: "link" %>

app/views/categories/new.html.erb
<div class="form">
  <h2>New Category</h2>
    <%= render 'form', category: @category %><br>
    <%= link_to 'Back', categories_path %>  
</div>

app/views/categories/show.html.erb
<li>		<%= link_to "edit", edit_category_path %>
    			</li> 
    			<li><%= link_to "Destroy", category_path(@category), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li> 

                  
<%= link_to "back", categories_path  %>

app/views/home/index.html.erb
<div class="hero">
        <nav>
            
            <div class="container h3">

                <%= link_to "Signup", "/accounts/sign_up", :class => "float-end text-white bg-dark text-decoration-none px-3" %>
            
            <%= link_to "Login", "/accounts/sign_in", :class => "float-end text-white bg-dark text-decoration-none" %>
            
            </div>
        </nav>

        <div class="lamp-container">
            <img src="https://i.postimg.cc/yYz5Nnqw/lamp.png" alt="" class="lamp">
            <img src="https://i.postimg.cc/SxgtDhXh/light.png" alt="" class="light" id="light">
        </div>

        <div class="text-container">
            <h1>Latest <br>  Technologies</h1>
            <p>Learn online classes to master popular programming languages, such as Java, Ruby, C#, PHP, C++, JQuery, and more. Beginner to advanced courses available..</p>
            <a href="">Check All Collections</a>
        </div>
    </div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>



    <%= yield %>
  </body>

</html>